### ISSUE TITLE
Give exception back to wasm

### ISSUE THREAD

**Issue by kleash** [hyperledger-labs/fabric-chaincode-wasm#11]
As of now, our shim wrapper functions for wasm does not give exception back. We are mostly ignoring exceptions or just returning -1 as function result.

For example ```__get_state``` wrapper for wasm: https://github.com/kleash/wasmer-chaincode-test/blob/bfc746d12cd70b67034fd9a5e83d37d26d14b0af/wasmcc/main.go#L98

Here we just ignore the error and returns -1 if we are unable to retrieve from the state.

A mechanism is required to propagate this exception back to wasm so that wasm chaincode developers can use the exception message and stack trace for debugging.

**Comment by MHBauer** [comment]
https://hacks.mozilla.org/2019/11/multi-value-all-the-wasm/
multi values might help with this and other things in the future. Maybe information to save for the future.

**Comment by kleash** [comment]
Yeah, this would be great.

But the blog points out that only Cranelift and Wasmtime supports it. Life doesn't support it as of now..

**Comment by syrusakbary** [comment]
Just randomly seen this. We will soon add support for multi-values in [Wasmer](https://github.com/wasmerio/wasmer) :)

**Comment by kleash** [comment]
@syrusakbary That seems interesting. We tried wasmer in our initial testing but it was not compatible with fabric sdk out of the box.

**Comment by syrusakbary** [comment]
> We tried wasmer in our initial testing but it was not compatible with fabric sdk out of the box

Wasmer supports Emscripten and WASI out of the box, but it should be very easy to plug new ABIs/SDKs. Let me know if we can help in any way, I'd be super happy to help!
