### ISSUE TITLE
tool to load the wasm

### ISSUE THREAD

**Issue by MHBauer** [hyperledger-labs/fabric-chaincode-wasm#3]
I think I can probably rig up a quick go-sdk client that will be able to interact with.

bonus, take a raw wasm in, and hex-encode it in this program.

args:
 - create
 - chaincode name
 - hex-encoded wasm binary 
 - varargs init args to wasm init function

@kleash I will try to do this, but if you want to do it and make it a deliverable you are responsible for, assign yourself and let us know.

**Comment by kleash** [comment]
This will be nice to have. I will try to do it, might help me in gaining some insights into go-sdk also.

If you have already started, then please go-ahead..
