### ISSUE TITLE
Step by Step Guide to create testnetwork and deploy and invoke wasm smart contract

### ISSUE THREAD

**Issue by mishaaaa** [hyperledger-labs/fabric-chaincode-wasm#37]
I would like to get a step by step guide for setting up a fabric test network and also on how to deploy the wasm chaincode to the test network.

**Comment by kleash** [comment]
Hi @mishaaaa 

You can use byfn guide to setup fabric test network from here: https://hyperledger-fabric.readthedocs.io/en/release-1.4/build_network.html

- On completion, go to your chaincode folder and clone this repo.
- Go to cli container using `docker exec -it cli bash`
- Once you are in cli, please follow this section of readme file: [end-2-end-example-with-byfn](https://github.com/hyperledger-labs/fabric-chaincode-wasm#end-2-end-example-with-byfn)
(You can start from step 2 of this guide)

**Comment by kleash** [comment]
Closing it due to inactivity. Let me know if need further help.
